# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mongo:3.6

    working_directory: ~/sample-server-user

    environment:
      MAVEN_OPTS: -Xmx3200m

    branches:
      only:
        - develop
        -  /feature/.*/

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies- # fallback to using the latest cache if no exact match is found
      - run: mvn clean
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn verify
